# Generated by Django 3.2 on 2022-03-27 20:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AddField(
            model_name='post',
            name='criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
