# Generated by Django 3.2 on 2022-03-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220327_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hora',
            field=models.TimeField(auto_now=True, verbose_name='horario'),
        ),
    ]
