# Generated by Django 3.2 on 2022-03-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Um pouco sobre o blog', max_length=255),
        ),
    ]
