# Generated by Django 3.2 on 2022-04-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220401_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_title',
            field=models.ImageField(blank=True, height_field=350, null=True, upload_to='images/', width_field=500),
        ),
    ]
