# Generated by Django 3.2 on 2022-04-01 21:53

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_header_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_title',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
