# Generated by Django 3.2 on 2022-04-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_comments_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='autor',
            field=models.CharField(max_length=255),
        ),
    ]
