# Generated by Django 3.2 on 2022-04-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_comments_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
